### ISSUE TITLE
The RFP link is no longer active

### ISSUE THREAD

**Issue by mgboydcom** [opendata/contracts#1]
Is there any chance of sharing the RFP document somehow, as the [link](https://screendoor.dobt.co/u-s-open-data-institute/document-authentication-system) has been taken down now that the project contract has been awarded, but that means others can't use the RFP as a starting point for similar projects.

**Comment by waldoj** [comment]
Good point! I didn't realize that the RFP would disappear from the public web. There's no great, simple way to render this RFP in a reasonable fashion to store here, but I'll take a crack at it. :)

**Comment by waldoj** [comment]
[It's better than nothing](https://github.com/opendata/contracts/blob/master/Data%20Authentication/RFP.md). :) Thanks for calling that up, @mgboydcom.
